# Generated by Django 5.2 on 2025-04-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_gardenitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="streak",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="GardenItem",
        ),
    ]
