# Generated by Django 5.2 on 2025-04-24 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_purchasableitem_customuser_theme_purchasehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasehistory",
            name="item",
        ),
        migrations.RemoveField(
            model_name="purchasehistory",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="theme",
        ),
        migrations.CreateModel(
            name="FavoriteSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_uri", models.URLField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PurchasableItem",
        ),
        migrations.DeleteModel(
            name="PurchaseHistory",
        ),
    ]
