# Generated by Django 5.1.3 on 2025-04-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_purchasehistory_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="accepted_privacy",
            field=models.BooleanField(default=False),
        ),
    ]
