# Generated by Django 5.2 on 2025-05-01 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_customuser_accepted_privacy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="accepted_privacy",
        ),
        migrations.AlterField(
            model_name="waterintakerecord",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="waterintakerecord",
            unique_together={("user", "date")},
        ),
    ]
